
# Support Kitty graphics protocol
set -as terminal-overrides ",*:Tc"
set -as terminal-features ",*:usstyle"
set -as terminal-features ",*:sixel"

# Allow Kitty graphics protocol passthrough (needed for fastfetch images)
set -g allow-passthrough on
set -as terminal-features ",*:RGB"
