cursor #f0dfd8
cursor_text_color #d7c2b9

foreground            #f0dfd8
background            #1a120d
selection_foreground  #432b1d
selection_background  #e6beab
url_color             #ffb68f

color0   #1a120d
color1   #ff7872
color2   #96ff7f
color3   #ffe572
color4   #f29f72
color5   #763816
color6   #ffb68f
color7   #fff5ef
color8   #a59d99
color9   #ffa39f
color10  #b6ffa5
color11  #ffeea5
color12  #ffc09f
color13  #ffcbb0
color14  #ffdecc
color15  #fffaf8
